RegisterNetEvent("br_interactions:handcuff")
AddEventHandler("br_interactions:handcuff", function (target, info)
    TriggerClientEvent("br_interactions:"..info.action, source, info.side, "active")
    TriggerClientEvent("br_interactions:"..info.action, target, info.side, "passive")
end)